name: Build AppImage
on:
  workflow_dispatch:
  schedule:
    - cron: "5 */12 * * *"
  push:
    branches:
      - "master"

permissions:
  contents: write

jobs:
  version:
    name: Cursor AppImage
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install desktop-file-utils zsync -y --no-install-recommends
      - uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
          ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: 'dist'

      - name: Release tag
        uses: ncipollo/release-action@v1
        with:
          name: Cursor AppImage ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          artifacts: |
            dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          removeArtifacts: true
          artifactErrorsFailBuild: true
          generateReleaseNotes: true

      - name: Release Continuous
        uses: ncipollo/release-action@v1
        with:
          name: Cursor AppImage Continuous Build
          artifacts: |
            dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          removeArtifacts: true
          artifactErrorsFailBuild: true
          generateReleaseNotes: true